[Paths] 
Prefix = C:/condaenvs/hazus_env/Library
Binaries = C:/condaenvs/hazus_env/Library/bin
Libraries = C:/condaenvs/hazus_env/Library/lib
Headers = C:/condaenvs/hazus_env/Library/include/qt
TargetSpec = win32-msvc
HostSpec = win32-msvc
